### ISSUE TITLE
Rotate -90deg

### ISSUE THREAD

**Issue by valentin-anamorphik** [mtgibbs/chartist-plugin-barlabels#6]
Hello

Is it possible to rotate the text?

Thanks.

![2019-04-25_12h14_53](https://user-images.githubusercontent.com/32865180/56729026-7f2bc700-6754-11e9-8170-7622c904a171.jpg)

**Comment by mtgibbs** [comment]
You should be able to just use CSS Transform.

By default, the label classes on these are `.ct-label-above` and `.ct-label-below` depending on whether you've crossed the threshold.

Just try:

```css
.ct-label-above, .ct-label-below {
   transform: rotate(-90deg);
}
```

**Comment by valentin-anamorphik** [comment]
thank you. But the origin is not correct.

```CSS
.ct-label-above, .ct-label-below {
transform: rotate(-10deg);
}
/*use transform-origin ? */
```

![2019-04-25_17h32_03](https://user-images.githubusercontent.com/32865180/56748618-7650ea80-6780-11e9-83a5-89bebc226d66.png)
